#page title
page_title                                : TimeSlicer                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6446266073                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : assets/presskit.zip                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : #assets/timeslicerappicon.jpg # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : #TimeSlicer                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : When scheduling your tasks becomes a task itself.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Navan Chauhan                                
your_link                                 : https://navan.website                    
your_city                                 : Boulder, CO                                
email_address                             : timeslicer@prudent.studio
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : PrudentStudio
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Timeboxing to the Rescue
    description                           : Best way to timebox and automagically schedule your tasks.
    fontawesome_icon_name                 : hourglass-start

  - title                                 : Multi-Calendar Support
    description                           : Works with any Calendar account added to your iPhone.
    fontawesome_icon_name                 : calendar-check
    
  - title                                 : On-Device Scheduling
    description                           : No information is sent to the cloud. All scheduling is done on the device itself.
    fontawesome_icon_name                 : mobile-alt

  - title                                 : Real-Time Sync
    description                           : Changes are instantly synced to your Calendar.
    fontawesome_icon_name                 : bolt

  - title                                 : Blackout Times
    description                           : Option to block out times when you don't want to be scheduled.
    fontawesome_icon_name                 : calendar-times

  - title                                 : Priority Scheduling
    description                           : Every task can be assigned a priority. The app will schedule the highest priority tasks first.
    fontawesome_icon_name                 : clipboard-check
  
  - title                                 : Aggressive Scheduling
    description                           : Option to aggressively schedule tasks, this will schedule tasks one after another.
    fontawesome_icon_name                 : toggle-on

  - title                                 : Relaxed Scheduling
    description                           : Option to space out all tasks evenly throughout the week.
    fontawesome_icon_name                 : toggle-off

  - title                                 : Mac Support
    description                           : The app is available on the Mac App Store. All your data is synced across devices.
    fontawesome_icon_name                 : laptop

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
